remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Parm Ghai
show_downloads: false 

description: >
  I'm a third year undergraduate student in the Mechanical Engineering program at the University of Toronto.
  <br><br>
  Feel free to reach out to me using my school email: parm.ghai@mail.utoronto.ca
  <br><br>
  <a href="https://www.linkedin.com/in/parmghai/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a>
  <a href="https://battlemonk345.itch.io/"> <img src="https://img.shields.io/badge/Itch.io-blue?logo=itch.io"> </a>
  <a href="https://github.com/Parm345"> <img src="https://img.shields.io/badge/GitHub-blue?logo=GitHub"> </a>
  